### ISSUE TITLE
Clarify pipeline from ChannelWorm to c302

### ISSUE THREAD

**Issue by gsarma** [openworm/ChannelWorm2#12]
We need to make explicit how c302 will access the ion channel models created in ChannelWorm.

@slarson @mwatts15 @rgerkin @pgleeson

**Comment by travs** [comment]
Is this just in terms of how to port the models to that project (could be done for example as a git submodule if they are checked into source control)? Bear with me I'm just getting my head back into this

**Comment by mwatts** [comment]
I believe you all have the wrong mark watts. @gsarma @slarson @rgerkin @pgleeson   I keep getting notifications for this project but I am not part of it nor as cool as it might be am i currently interested in it.

**Comment by travs** [comment]
@mwatts Sorry Mark :) we were looking for @mwatts15

**Comment by gsarma** [comment]
@travs nice to have you back! the issue here is exactly how c302 will access the NML files corresponding to channel models.  Right now, there are no channel models in c302, so it is not an issue.  But eventually, we will have quite a few. 

One consideration is to eliminate redundancy and prevent a situation where the models are out of sync in different repos.  If c302 queries PyOpenWorm to retrieve models, that may be a way to eliminate this situation, rather than maintain multiple copies under version control as text files.

**Comment by pgleeson** [comment]
@gsarma @travs Just to clarify... There are channels in c302, they're here: https://github.com/openworm/c302/blob/master/c302/cell_C.xml#L18 and get included when the configuration of c302 generated ([C or D based, see here](https://github.com/openworm/c302/blob/master/examples/summary/README.md)) requires them, e.g. see [here](https://github.com/openworm/c302/blob/master/examples/c302_C0_IClamp.net.nml#L57).

The idea of taking these over automatically from c302 to ChannelWorm or vice versa, doesn't make sense just yet... c302 is still in development, so all the model files there are likely to update at any time. 

Ideally, there will be a set of stable, NML2 compliant, experimentally constrained ion channels which will emerge from the ChannelWorm subproject which can be used in c302 at a later date, but simply automatising this process is not wise; a version of the ion channels which is "good enough for now" is used in c302 and the cell models can be built/tested based on these. When there are a better set from ChannelWorm, they can be replaced, but this will cause all neurons/networks to change behaviour. 

So it's not a problem looking for a technical solution of syncing between the projects, it's more that each side needs to reach a point where they are confident of that module, and it can be manually updated.

**Comment by gsarma** [comment]
@pgleeson @travs thank you for the clarification Padraig.  That's really the answer I was looking for.  I wasn't imagining a technical solution so much as a mutual understanding of what the pipeline would be.  

I'm going to close the issue for now and we can revisit at a later date as we make more progress.
